# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/danrudolf2/test-spec-repo.git'
#source 'https://github.com/CocoaPods/Specs.git'

target 'TestNativeSDK' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'FBLazyVector'
  pod 'FBReactNativeSpec'
  pod 'hermes-engine'
  pod 'RCTRequired'
  pod 'RCTTypeSafety'
  pod 'FBLazyVector'
  pod 'React'
  pod 'React-bridging'
  pod 'React-callinvoker'
  pod 'React-Core'
  pod 'React-CoreModules'
  pod 'React-cxxreact'
  pod 'React-hermes'
  pod 'React-jsi'
  pod 'React-jsiexecutor'
  pod 'React-jsinspector'
  pod 'React-logger'
  pod 'React-perflogger'
  pod 'React-RCTActionSheet'
  pod 'React-RCTAnimation'
  pod 'React-RCTBlob'
  pod 'React-RCTFabric'
  pod 'React-RCTImage'
  pod 'React-RCTLinking'
  pod 'React-RCTNetwork'
  pod 'React-RCTPushNotification'
  pod 'React-RCTSettings'
  pod 'React-RCTText'
  pod 'React-RCTVibration'
  pod 'React-rncore'
  pod 'React-runtimeexecutor'
  pod 'ReactCommon'
  pod 'Yoga'
  pod 'fmt'
  pod 'boost'
  pod 'DoubleConversion'
  pod 'RCT-Folly'
  pod 'React-graphics'
  
end
